services:
  searxiv:
    build: .
    platform: linux/amd64
    ports:
      - "1818:1818"
    volumes:
      - ./data/index:/root/.cache/searxiv
    env_file:
      - .env
    environment:
      - SEARXIV_DATABASE_URL=$SEARXIV_DATABASE_URL
      - SEARXIV_DICTIONARIES_PATH=/dictionaries
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:16.0
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./shared/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    env_file:
      - .env
    healthcheck:
      test: "pg_isready --username=postgres && psql --username=postgres --list"
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s
    userns_mode: "keep-id"
